In [ ]:
# Train Test Split In Data Set

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv("Boston.csv")
dataset.head(3)

,CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7

In [7]:
input_data = dataset.iloc[:,:-1]
output_data = dataset["MEDV"]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.25)

In [10]:
x_train

,CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
442,5.66637,0.0,18.10,0,0.740,6.219,100.0,2.0048,24,666.0,20.2,395.69,16.59
117,0.15098,0.0,10.01,0,0.547,6.021,82.6,2.7474,6,432.0,17.8,394.51,10.30
344,0.03049,55.0,3.78,0,0.484,6.874,28.1,6.4654,5,370.0,17.6,387.97,4.61
97,0.12083,0.0,2.89,0,0.445,8.069,76.0,3.4952,2,276.0,18.0,396.90,4.21
14,0.63796,0.0,8.14,0,0.538,6.096,84.5,4.4619,4,307.0,21.0,380.02,10.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,0.22212,0.0,10.01,0,0.547,6.092,95.4,2.5480,6,432.0,17.8,396.90,17.09
349,0.02899,40.0,1.25,0,0.429,6.939,34.5,8.7921,1,335.0,19.7,389.85,5.89
496,0.28960,0.0,9.69,0,0.585,5.390,72.9,2.7986,6,391.0,19.2,396.90,21.14
384,20.08490,0.0,18.10,0,0.700,4.368,91.2,1.4395,24,666.0,20.2,285.83,30.63
452,5.09017,0.0,18.10,0,0.713,6.297,91.8,2.3682,24,666.0,20.2,385.09,17.27

In [14]:
y_train

442    18.4
117    19.2
344    31.2
97     38.7
14     18.2
       ...
113    18.7
349    26.6
496    19.7
384     8.8
452    16.1
Name: MEDV, Length: 379, dtype: float64

In [15]:
x_test

,CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
143,4.09740,0.0,19.58,0,0.8710,5.468,100.0,1.4118,5,403.0,14.7,396.90,26.42
241,0.10612,30.0,4.93,0,0.4280,6.095,65.1,6.3361,6,300.0,16.6,394.62,12.40
309,0.34940,0.0,9.90,0,0.5440,5.972,76.7,3.1025,4,304.0,18.4,396.24,9.97
351,0.07950,60.0,1.69,0,0.4110,6.579,35.9,10.7103,4,411.0,18.3,370.78,5.49
106,0.17120,0.0,8.56,0,0.5200,5.836,91.9,2.2110,5,384.0,20.9,395.67,18.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,13.91340,0.0,18.10,0,0.7130,6.208,95.0,2.2222,24,666.0,20.2,100.63,15.17
109,0.26363,0.0,8.56,0,0.5200,6.229,91.2,2.5451,5,384.0,20.9,391.23,15.55
146,2.15505,0.0,19.58,0,0.8710,5.628,100.0,1.5166,5,403.0,14.7,169.27,16.65
411,14.05070,0.0,18.10,0,0.5970,6.657,100.0,1.5275,24,666.0,20.2,35.05,21.22
332,0.03466,35.0,6.06,0,0.4379,6.031,23.3,6.6407,1,304.0,16.9,362.25,7.83

In [12]:
y_test

143    15.6
241    20.1
309    20.3
351    24.1
106    19.5
       ...
434    11.7
109    19.4
146    15.6
411    17.2
332    19.4
Name: MEDV, Length: 127, dtype: float64

In [16]:
dataset.shape

(506, 14)

In [18]:
x_train.shape, y_train.shape

((379, 13), (379,))

In [19]:
x_test.shape, y_test.shape

((127, 13), (127,))