In [ ]:
# Handling Duplicate Data

In [6]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [25]:
data = {"name":["a", "b", "c", "d", "a", "c"], "eng":[8, 7, 5, 8, 8, 5], "hindi":[2, 3, 4, 5, 2, 6]}

In [35]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    5      6

In [32]:
df.drop_duplicates()

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [40]:
df.drop_duplicates(inplace=True)

In [39]:
df.drop_duplicates(keep="first")

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [27]:
df["duplicated"] = df.duplicated()

In [41]:
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [42]:
dataset = pd.read_csv("loan.csv")
dataset.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [43]:
dataset.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
609    False
610    False
611    False
612    False
613    False
Length: 614, dtype: bool

In [44]:
dataset.shape

(614, 13)

In [45]:
dataset.drop_duplicates(inplace=True)

In [46]:
dataset.shape

(614, 13)