In [ ]:
# Max Voting Averaging & Weighted Average Voting - Classification

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_moons

C:\Users\PRANAV\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
dataset = pd.read_csv("placements.csv")
dataset.head(3)

   cgpa  package
0   6.8     6.15
1   5.9     5.30
2   5.3     6.05

In [5]:
x = dataset.iloc[:,:-1]
y = dataset["package"]

In [6]:
x

    cgpa
0    6.8
1    5.9
2    5.3
3    7.4
4    5.8
..   ...
95   4.3
96   4.4
97   6.7
98   6.3
99   6.2

[100 rows x 1 columns]

In [7]:
y

0      6.15
1      5.30
2      6.05
3      6.60
4      7.10
      ...
95    10.00
96     2.10
97     9.10
98     5.15
99     5.65
Name: package, Length: 100, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [13]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.score(x_train, y_train)*100, lr.score(x_test, y_test)*100

(0.4297427256854225, -4.67576396859164)

In [14]:
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)
dt.score(x_train, y_train)*100, dt.score(x_test, y_test)*100

(45.43080916736305, -31.757417720687187)

In [23]:
svr = SVR()
svr.fit(x_train, y_train)
svr.score(x_train, y_train)*100, svr.score(x_test, y_test)*100

(2.560277879227091, -25.670727738397403)

In [16]:
from sklearn.ensemble import VotingRegressor

In [17]:
li = [("lr1", LinearRegression()), ("dt1", DecisionTreeRegressor()), ("svr1", SVR())]

In [20]:
vr = VotingRegressor(li, weights=[10, 20, 30])
vr.fit(x_train, y_train)

VotingRegressor(estimators=[('lr1', LinearRegression()),
                            ('dt1', DecisionTreeRegressor()), ('svr1', SVR())],
                weights=[10, 20, 30])

In [19]:
vr.score(x_train, y_train)*100, vr.score(x_test, y_test)*100

(26.494425961917468, -7.8178963952870495)

In [24]:
df = {"lr":lr.predict(x_test), "dt":dt.predict(x_test), "svr":svr.predict(x_test), "vr":vr.predict(x_test)}

In [26]:
pd.DataFrame(df).head(3)

         lr     dt       svr        vr
0  6.081812  7.900  6.634422  6.964180
1  5.992706  7.875  6.115498  6.681533
2  6.215471  5.775  6.300098  6.110961

In [27]:
(6.081812+7.900+6.634422)/3

6.872078000000001